apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "external-secrets-rancher-store-operator.fullname" . }}-app
  labels:
    {{- include "external-secrets-rancher-store-operator.labels" . | nindent 4 }}
data:
  server.js: |
    // server.js
    const http = require('http');
    const port = 8080;

    const requestHandler = (request, response) => {
      response.end('Hello, World!');
    };

    const server = http.createServer(requestHandler);

    server.listen(port, (err) => {
      if (err) {
        return console.log('something bad happened', err);
      }

      console.log(`server is listening on ${port}`);
    });
