apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: {{ include "external-secrets-rancher-store-operator.fullname" . }}
spec:
  generateSelector: false
  resources:
    - apiVersion: v1
      resource: secrets
      labelSelector:
        matchExpressions:
          - { key: 'cluster.x-k8s.io/cluster-name', operator: Exists }
  attachments:
    - apiVersion: v1
      resource: configmaps
      updateStrategy:
        method: InPlace
    - apiVersion: external-secrets.io/v1beta1
      resource: clustersecretstores
      updateStrategy:
        method: InPlace
  hooks:
    sync:
      webhook:
        url: http://{{ include "external-secrets-rancher-store-operator.fullname" . }}.{{ .Release.Namespace }}/sync